---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(viridis)
library(Hmisc)
library(reshape2) 
library(reshape) 
library(ggh4x)
library(tidyverse)
library(cowplot)
```

```{r}
facet_nested_theme <- theme(
    strip.background = element_rect(fill = "white", colour = "grey", linetype="dotted", size = 0.2, linewidth=30), 
    panel.background = element_rect(fill='white', color='grey'),
    panel.border = element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    legend.key = element_rect(color = "transparent"),
    panel.spacing.x = unit(0,"line"),
    panel.spacing.y = unit(0,"line"))
```
# task counts

## read data
```{r}

tasks_df <- read.table("munged_basic_tasks.dat", h=T)
tasks_df <- subset(tasks_df, update <= 100000)
tasks_df$task <- factor(tasks_df$task, levels = c("NOT", "NAND", "OR_NOT", "AND", "OR", "AND_NOT", "NOR", "XOR", "EQU"))
```



## per update

```{r}
task_hist_plotter <- function(o="Host", t="parasites"){
  
  plot <- tasks_df %>% filter(partner == o) %>% filter(treatment == t) %>% 
    group_by(rep) %>%
    ggplot(aes(update, task_count)) + 
    geom_area(aes(fill=task), position='stack') +
    ylab("Count of task completions") + xlab("Updates") +
    facet_wrap(~rep) + 
    facet_nested_theme + 
    scale_fill_manual(name="Task",values=turbo(10)) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    ggtitle(paste(o,t))
  return(plot)
}
```

```{r}
#host_plot1 <- task_hist_plotter("Host", "mutualists-grid")
#plot1 <- plot_grid(host_plot1)

#sym_plot1 <- task_hist_plotter("Sym", "mutualists-grid")
#plot2 <- plot_grid(sym_plot1)

#host_plot2 <- task_hist_plotter("Host", "mutualists-mixed")
#plot3 <- plot_grid(host_plot2)

#sym_plot2 <- task_hist_plotter("Sym", "mutualists-mixed")
#plot4 <- plot_grid(sym_plot2)

host_plot3 <- task_hist_plotter("Host", "nosyms-grid-diff")
plot1 <- plot_grid(host_plot3)

sym_plot3 <- task_hist_plotter("Sym", "nosyms-grid-diff")
plot2 <- plot_grid(sym_plot3)

plot_grid( byrow = FALSE, ncol = 1, nrow = 2,
  plotlist = list(plot1, plot2))
```
