---
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(viridis)
library(Hmisc)
library(reshape2) 
library(reshape) 
library(ggh4x)
library(tidyverse)
library(cowplot)
```
```{r}
facet_nested_theme <- theme(
    strip.background = element_rect(fill = "white", colour = "grey", linetype="solid", size = 0.2, linewidth=30), 
    panel.background = element_rect(fill='white', color='grey'),
    panel.border = element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    legend.key = element_rect(color = "transparent"),
    panel.spacing.x = unit(0,"line"),
    panel.spacing.y = unit(0,"line"))
```
# task counts
## read data
```{r}
tasks_df <- read.table("munged_transmission_rates.dat", h=T)
tasks_df <- subset(tasks_df, update <= 100000)

# reshape from wide (one column per metric) to long (one row per metric per update)
tasks_long <- tasks_df %>%
  pivot_longer(
    cols = c(horiz_attempts, horiz_successes, vert_attempts, vert_successes),
    names_to = "metric",
    values_to = "count"
  )

tasks_long$metric <- factor(tasks_long$metric, 
                             levels = c("horiz_attempts", "horiz_successes", 
                                        "vert_attempts", "vert_successes"))
```
## per update
```{r}
task_hist_plotter <- function(t="parasites"){
  
  plot <- tasks_long %>% filter(treatment == t) %>% 
    group_by(rep) %>%
    ggplot(aes(update, count, color=metric, group=metric)) + 
    geom_line() +
    ylab("Transmissions") + xlab("Updates") +
    facet_wrap(~rep, ncol = 2) + 
    facet_nested_theme + 
    scale_color_manual(values=viridis(4)) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    ggtitle(t)
  return(plot)
}
```
```{r}
plot1 <- plot_grid(task_hist_plotter("mutualists-grid"))
plot3 <- plot_grid(task_hist_plotter("mutualists-mixed"))

final_plot <- plot_grid( byrow = FALSE, ncol = 2, nrow = 1,
  plotlist = list(plot1, plot3))
ggsave("transmissions.pdf", plot = final_plot, width = 14, height = 14, units = "in")

```